<?php

namespace Symfony\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productRepository extends EntityRepository
{
}
